language: ruby
branches:
  only:
    - master
services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker build --no-cache -t cloudqq/redis-ts .
  - docker tag cloudqq/redis-ts:latest cloudqq/redis-ts:v1
  - docker push cloudqq/redis-ts:latest
